[HOTFIX] Fix infection anomalies failing to be removed (#4452)
## Short description

TL;DR is we have some Far Horizons code that wasn't updated. I just
updated it.

Port of https://github.com/Far-Horizons-SS14/Far-Horizons-SS14/pull/645

FH Commits 63f9d4e2876c0d14b0e4f512769c2e7a3b5ca0d0 and
13533314641bb1ec22421d747ad74953f0b5701b

## Why we need to add this
<!-- What is the reason for adding these changes? Please post links to
Discussions as well as Bug Reports here. Please describe how this will
change the game balance. -->

Exceptions are being thrown when removing infection anomalies:

```
Caught exception in entsys
System.InvalidOperationException: Removing a component, Robust.Server.GameObjects.PointLightComponent before it has been added is probably not what you wanted to do. Target entity was Artemy Stamatin (3998970/n3998970, MobHuman, IamDaniel).
   at Robust.Shared.GameObjects.EntityManager.ThrowPreAddRemovalException(EntityUid target, IComponent component) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.Components.cs:line 626
   at Robust.Shared.GameObjects.EntityManager.RemoveComponentImmediate(EntityUid uid, IComponent component, CompIdx idx, Boolean terminating, MetaDataComponent meta) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.Components.cs:line 642
   at Content.Server.Anomaly.Effects.InnerBodyAnomalySystem.RemoveComponents(EntityUid target, ComponentRegistry components) in /home/runner/work/space-station-14/space-station-14/Content.Server/Anomaly/Effects/InnerBodyAnomalySystem.cs:line 261
   at Content.Server.Anomaly.Effects.InnerBodyAnomalySystem.RemoveAnomalyFromBody(Entity`1 ent) in /home/runner/work/space-station-14/space-station-14/Content.Server/Anomaly/Effects/InnerBodyAnomalySystem.cs:line 218
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass57_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, Unit& ev) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 305
   at Robust.Shared.GameObjects.EntityEventBus.EntDispatch(EntityUid euid, Type eventType, Unit& args) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 572
   at Content.Shared.Anomaly.SharedAnomalySystem.EndAnomaly(EntityUid uid, AnomalyComponent component, Boolean supercritical, Boolean spawnCore, Boolean logged) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Anomaly/SharedAnomalySystem.cs:line 206
```

Occurences of "Ending anomaly" last 24h:

<img width="1837" height="244" alt="image"
src="https://github.com/user-attachments/assets/4d6abef5-92b4-4565-a822-2ce71a42e54c"
/>

Bug reports:

- https://discord.com/channels/1272545509562777621/1504756751243677717
- https://discord.com/channels/1272545509562777621/1504601563531055214
- https://discord.com/channels/1272545509562777621/1504577097476083853
- https://discord.com/channels/1272545509562777621/1504565755847508129

If an infection anomaly crits, it doesn't remove, it instead just crits
infinitely.

## Media (Video/Screenshots)
<!--
If your PR contains in-game changes you must provide screenshots/videos
of the changes.
-->

N/a

Exceptions were thrown before, none are thrown after.

## Checks
<!-- check boxes for faster reviewing of your PR -->

- [x] I do not require assistance to complete the PR.
- [x] Before posting/requesting review of a PR, I have verified that the
changes work.
- [x] I have added screenshots/videos of the changes, or this PR does
not change in-game mechanics.
- [x] I affirm that my changes are licensed under the [MIT
License](https://github.com/ss14Starlight/space-station-14/blob/Starlight/LICENSE.TXT)
and grant permission for use in this repository under its conditions.

**Changelog**
<!--
If you want the players to know about changes made in this PR, specify
them using the template outside the comment. Short and informative. -->

:cl: Rinary
- fix: Infection anomalies can actually be removed.

---------

Co-authored-by: Rinary <rinary.super@gmail.com>